#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
COPY src /users/klevin/repomanagement/src
COPY pom.xml /users/klevin/repomanagement
RUN mvn  -f /users/klevin/repomanagement/pom.xml release:prepare release:perform -DskipTests -Darguments="-Dmaven.repo.local=/users/klevin/.m2"

#
# Package stage
#
FROM openjdk:11-jre-slim
COPY --from=build /users/klevin/repomanagement/target/RepositoryManagementProject-1.0.18-SNAPSHOT.jar /usr/local/lib/repomanagement.jar
EXPOSE 8088
ENTRYPOINT ["java","-jar","/usr/local/lib/repomanagement.jar"]